import type { PurchaseKindId, PurchaseStatusId } from "@/lib/billing/purchase";
import type { PublicationState } from "@/types/published";

/**
 * TEXTOS de la consola interna (es-MX). Módulo de copy central del área (facilita i18n futura). La consola es de uso interno y algo
 * más densa que el panel de clientes; el lenguaje sigue siendo el del producto. Los nombres de plan salen de `planLabel`.
 */
export const adminCopy = {
  badge: "ADMIN",
  consoleLabel: "Consola de administración",
  menuLink: "Administración",
  backToPanel: "Volver al panel",
  skip: "Saltar al contenido",
  openMenu: "Abrir menú",
  closeMenu: "Cerrar menú",
  navLabel: "Administración",

  nav: { overview: "Resumen", users: "Usuarios", events: "Eventos", templates: "Plantillas", purchases: "Compras", webhooks: "Webhooks", audit: "Auditoría" },

  common: {
    search: "Buscar",
    filter: "Filtrar",
    clear: "Limpiar",
    all: "Todos",
    none: "—",
    yes: "Sí",
    no: "No",
    sort: "Orden",
    newest: "Más recientes",
    oldest: "Más antiguos",
    eventDate: "Fecha del evento",
    previous: "Anterior",
    next: "Siguiente",
    pageOf: (page: number, count: number) => `Página ${page} de ${count}`,
    results: (total: number) => (total === 1 ? "1 resultado" : `${total.toLocaleString("es-MX")} resultados`),
    noResults: "No hay resultados con estos filtros.",
    pagination: "Paginación",
    filters: "Filtros",
    details: "Ver detalle",
    unnamed: "Sin nombre",
    readOnly: "Solo lectura",
  },

  overview: {
    title: "Resumen",
    description: "Estado general del producto, calculado con datos reales.",
    metrics: "Cifras del producto",
    users: "Usuarios",
    events: "Eventos",
    publishedInvitations: "Invitaciones publicadas",
    guests: "Invitados",
    rsvps: "RSVP recibidos",
    paidPurchases: "Compras pagadas",
    plansTitle: "Eventos por plan efectivo",
    plansHint: "El plan de un evento es el mayor plan de sus compras pagadas.",
    revenueTitle: "Ingresos",
    revenueHint: "Solo compras pagadas. Los reembolsos, cancelaciones, pagos fallidos y pendientes no cuentan.",
    revenueTotal: "Ingresos brutos registrados",
    revenue30: "Últimos 30 días",
    revenueCount: (count: number) => (count === 1 ? "1 compra" : `${count.toLocaleString("es-MX")} compras`),
    otherCurrencies: "Compras en otras monedas (no se suman ni se convierten):",
    purchaseMixTitle: "Compras pagadas por tipo",
    essential: "Compras Esencial",
    premium: "Compras Premium",
    upgrades: "Mejoras (Esencial → Premium)",
    accessTitle: "Acceso de eventos de pago",
    expiringSoon: (days: number) => `Acceso termina en los próximos ${days} días`,
    expired: "Eventos de pago con acceso vencido",
    accessNote: "Todavía no se bloquea la invitación pública al vencer: es un dato para preparar la política.",
    mediaTitle: "Archivos",
    mediaCount: "Archivos guardados",
    mediaSize: "Tamaño aproximado",
    mediaStale: (hours: number) => `Subidas sin verificar (más de ${hours} h)`,
    mediaUnreferenced: "Posibles huérfanos (verificados, sin referencia)",
    mediaUnavailable: "No disponible",
    mediaNote: "Diagnóstico informativo: no se borra nada automáticamente.",
    orphans: {
      analyze: "Analizar huérfanos",
      analyzing: "Analizando…",
      result: (count: number, size: string) => (count === 0 ? "No hay archivos huérfanos." : `${count.toLocaleString("es-MX")} archivos huérfanos (≈ ${size}).`),
      pending: (count: number, hours: number) => `Subidas sin verificar (más de ${hours} h): ${count.toLocaleString("es-MX")}`,
      unreferenced: (count: number, hours: number) => `Verificados sin referencia (más de ${hours} h): ${count.toLocaleString("es-MX")}`,
      truncated: (limit: number) => `Cada limpieza procesa un lote de ${limit}; repítela hasta que no queden.`,
      manualCleanup: "Solo análisis. La limpieza es manual: npm run media:orphans (con análisis previo y confirmación).",
      error: "No pudimos analizar los archivos. Inténtalo de nuevo.",
    },
    healthTitle: "Salud del sistema",
    healthNote: "Solo indica si hay configuración; nunca muestra valores.",
    activityTitle: "Actividad reciente",
    recentUsers: "Nuevos usuarios",
    recentEvents: "Eventos creados",
    recentPublications: "Publicaciones",
    recentPurchases: "Compras",
    recentWebhooks: "Webhooks",
    noActivity: "Sin actividad todavía.",
    versionLabel: (version: number) => `Versión ${version}`,
  },

  health: {
    database: "Base de datos",
    storage: "Almacenamiento de imágenes",
    clerk: "Clerk (acceso)",
    stripe: "Stripe (pagos)",
    configured: "Configurado",
    notConfigured: "No configurado",
    missing: (names: readonly string[]) => `Falta: ${names.join(", ")}`,
  },

  users: {
    title: "Usuarios",
    description: "Cuentas registradas. Los planes son por evento, no por usuario.",
    searchLabel: "Buscar por nombre o correo",
    caption: "Usuarios registrados",
    user: "Usuario",
    email: "Correo",
    events: "Eventos",
    paidEvents: "De pago",
    createdAt: "Registro",
    role: "Rol",
    detailTitle: "Usuario",
    identity: "Cuenta",
    name: "Nombre",
    clerk: "Conexión con Clerk",
    clerkLinked: "Vinculada",
    clerkUnlinked: "Sin vincular",
    stripeCustomer: "Cliente de Stripe",
    eventsTitle: "Eventos",
    eventsCaption: "Eventos de este usuario",
    eventsLimit: (shown: number, total: number) => `Se muestran los ${shown} más recientes de ${total}.`,
    noEvents: "Este usuario todavía no tiene eventos.",
    roleNote: "El rol es de solo lectura. Para conceder acceso de administración se cambia a mano en la base de datos (docs/ADMIN.md).",
  },

  events: {
    title: "Eventos",
    description: "Todos los eventos, con su plan efectivo y su estado de publicación.",
    searchLabel: "Buscar por evento, enlace o propietario",
    publication: "Publicación",
    type: "Tipo",
    plan: "Plan",
    caption: "Eventos",
    event: "Evento",
    owner: "Propietario",
    template: "Plantilla",
    effectivePlan: "Plan efectivo",
    publicationState: "Publicación",
    eventDate: "Fecha del evento",
    createdAt: "Creado",
    detailTitle: "Evento",
    summary: "Resumen del evento",
    slug: "Enlace público",
    publishedVersion: "Versión publicada",
    neverPublished: "Sin publicar",
    paidAccessUntil: "Acceso pagado hasta",
    access: "Acceso",
    accessActive: "Activo",
    accessExpired: "Expirado",
    accessFree: "Sin compra",
    guests: "Invitados",
    rsvpSummary: "Confirmaciones (RSVP)",
    rsvpReceived: "RSVP recibidos",
    confirmed: "Confirmados",
    declined: "No asistirán",
    pending: "Pendientes",
    pendingNote: "«Tal vez» cuenta como pendiente.",
    gallery: "Imágenes de galería",
    media: "Archivos",
    updatedAt: "Actualizado",
    purchasesTitle: "Historial de compras",
    purchasesCaption: "Compras de este evento, de la más antigua a la más reciente",
    noPurchases: "Este evento no tiene compras: es Gratis.",
    privacyNote: "Por privacidad, la consola solo muestra conteos de invitados: nunca nombres, correos, teléfonos, mensajes ni enlaces personalizados.",
    noInvitation: "Sin invitación",
    timezone: "Zona horaria",
  },

  publication: {
    draft: "Borrador",
    published: "Publicado",
    changes: "Cambios sin publicar",
  } satisfies Record<PublicationState, string>,

  templates: {
    title: "Plantillas",
    description: "Catálogo de plantillas. Aquí solo se cambian la visibilidad y el plan mínimo del evento.",
    caption: "Plantillas del catálogo",
    name: "Nombre",
    slug: "Enlace",
    eventType: "Tipo de evento",
    design: "Diseño",
    visibility: "Visibilidad",
    minimumPlan: "Plan mínimo del evento",
    invitations: "Invitaciones",
    actions: "Acciones",
    edit: "Editar",
    editTitle: (name: string) => `Editar ${name}`,
    editDescription: "El nombre, el enlace y el estado del diseño no se pueden cambiar desde aquí.",
    visibilityLabel: "Visibilidad en el catálogo",
    minimumPlanLabel: "Plan mínimo del evento",
    minimumPlanHint: "Es el plan mínimo que necesita un evento para usar la plantilla. No modifica los eventos que ya existen.",
    save: "Guardar cambios",
    saving: "Guardando…",
    cancel: "Cancelar",
    back: "Volver",
    confirm: "Confirmar",
    confirmTitle: "Confirma el cambio",
    hideConfirm: (name: string) => `¿Ocultar ${name} del catálogo?`,
    hideNote: "Las invitaciones ya existentes seguirán funcionando.",
    planNote: "Este cambio solo afectará nuevas selecciones.",
    noChanges: "No hay cambios que guardar.",
    saved: (name: string) => `Se guardaron los cambios de ${name}.`,
    errors: {
      forbidden: "No tienes permiso para hacer esto.",
      invalid: "Los valores no son válidos.",
      not_found: "No encontramos esa plantilla.",
      unavailable: "No pudimos guardar el cambio. Inténtalo de nuevo.",
    },
    designStatus: { IMPLEMENTED: "Diseño terminado", CONCEPT: "Concepto", COMING_SOON: "Próximamente" },
    publicationStatus: { PUBLISHED: "Visible en el catálogo", DRAFT: "Oculta", ARCHIVED: "Archivada" },
    publicationShort: { PUBLISHED: "Visible", DRAFT: "Oculta", ARCHIVED: "Archivada" },
  },

  purchases: {
    title: "Compras",
    description: "Compras por evento. La consola solo las consulta: el proveedor de pagos y su webhook son la autoridad.",
    searchLabel: "Buscar por evento o usuario",
    status: "Estado",
    kind: "Tipo",
    plan: "Plan",
    caption: "Compras",
    event: "Evento",
    user: "Usuario",
    amount: "Importe",
    currency: "Moneda",
    provider: "Proveedor",
    date: "Fecha",
    detailTitle: "Compra",
    paidAt: "Pagada el",
    createdAt: "Creada el",
    updatedAt: "Actualizada el",
    accessStartsAt: "Acceso desde",
    accessEndsAt: "Acceso hasta",
    checkoutSession: "Sesión de pago",
    paymentIntent: "Pago (intent)",
    stripeCustomer: "Cliente de Stripe",
    stripeCustomerPresent: "Presente",
    stripeCustomerAbsent: "No registrado",
    externalIdsNote: "Los identificadores del proveedor se muestran parcialmente, solo para soporte.",
    readOnlyNote: "La consola no marca pagos, no crea planes ni reembolsa: el proveedor y su webhook son la autoridad.",
    statusLabel: {
      PENDING: "Pendiente",
      PAID: "Pagada",
      FAILED: "Fallida",
      REFUNDED: "Reembolsada",
      CANCELED: "Cancelada",
    } satisfies Record<PurchaseStatusId, string>,
    kindLabel: { INITIAL: "Inicial", UPGRADE: "Mejora" } satisfies Record<PurchaseKindId, string>,
    providers: { STRIPE: "Stripe", MERCADO_PAGO: "Mercado Pago" },
  },

  webhooks: {
    title: "Webhooks",
    description: "Eventos del proveedor de pagos ya procesados.",
    searchLabel: "Buscar por tipo de evento",
    caption: "Eventos de webhook procesados",
    provider: "Proveedor",
    externalId: "Evento",
    type: "Tipo",
    date: "Fecha",
    state: "Estado",
    processed: "Procesado",
    note: "Solo se guardan los eventos procesados (id, tipo y fecha). Los ignorados o con error no se registran, y nunca se guarda el contenido ni la firma.",
  },

  audit: {
    title: "Auditoría",
    description: "Cambios hechos desde la consola de administración (los más recientes primero).",
    caption: "Acciones de administración",
    date: "Fecha",
    actor: "Administrador",
    target: "Elemento",
    changes: "Cambio",
    empty: "Todavía no hay cambios registrados.",
    note: "Solo se registran las acciones que modifican algo (hoy, la visibilidad y el plan mínimo de una plantilla), con el antes y el después. Sin datos personales.",
    recent: "Cambios de administración",
    fields: { publicationStatus: "Visibilidad", minimumPlan: "Plan mínimo" },
    templateTarget: (name: string | null) => (name ? `Plantilla · ${name}` : "Plantilla"),
  },

  roles: { USER: "Usuario", ADMIN: "Administrador" },
} as const;
